const getAllBattles = async (): Promise<{ battles: Battle[] }> => {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 1000));

  // Return mock data
  return {
    battles: [
      {
        _id: "battle1",
        topic: "Who is the perfect character in the series F.R.I.E.N.D.S",
        model1: "llama8b",
        model2: "mistral",
        judge: "gemma",
        rounds: 6,
        winner: "llama8b",
        score: 9,
        loserScore: 7,
        createdAt: "2025-04-18T14:22:33Z",
        likeCount: 42,
        dislikeCount: 3,
        userReaction: null,
      },
      {
        _id: "battle2",
        topic: "Is AI consciousness possible?",
        model1: "gemma",
        model2: "llama8b",
        judge: "claude",
        rounds: 4,
        winner: null,
        createdAt: "2025-04-19T09:12:45Z",
        likeCount: 28,
        dislikeCount: 5,
        userReaction: null,
      },
      {
        _id: "battle3",
        topic: "Should pizza have pineapple on it?",
        model1: "mistral",
        model2: "claude",
        judge: "gemma",
        rounds: 8,
        winner: "claude",
        score: 8,
        loserScore: 6,
        createdAt: "2025-04-15T18:34:21Z",
        likeCount: 156,
        dislikeCount: 42,
        userReaction: null,
      },
      {
        _id: "battle4",
        topic: "Is remote work better than office work?",
        model1: "llama8b",
        model2: "claude",
        judge: "gemma",
        rounds: 5,
        winner: "claude",
        score: 9,
        loserScore: 8,
        createdAt: "2025-04-20T07:45:12Z",
        likeCount: 17,
        dislikeCount: 2,
        userReaction: null,
      },
      {
        _id: "battle5",
        topic: "Batman vs Superman: Who would win?",
        model1: "mistral",
        model2: "llama8b",
        judge: "claude",
        rounds: 6,
        winner: "mistral",
        score: 9,
        loserScore: 7,
        createdAt: "2025-04-17T12:30:45Z",
        likeCount: 87,
        dislikeCount: 23,
        userReaction: null,
      },
      {
        _id: "battle6",
        topic: "Is coffee better than tea?",
        model1: "claude",
        model2: "gemma",
        judge: "mistral",
        rounds: 4,
        winner: null,
        createdAt: "2025-04-19T15:22:18Z",
        likeCount: 34,
        dislikeCount: 8,
        userReaction: null,
      },
    ],
  };
};

export default getAllBattles;
